#!/bin/bash
set -e

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "usage: source login"
    exit 1
fi

set -x

gpg --batch --yes -o cji.tar.gz -d cji.tar.gz.gpg
tar -vxzf cji.tar.gz
shred -vzuf cji.tar.gz
cd home/cji
source .bashrc
